max_bandwidth = 20
median_computation_delay = 2.5
no_of_episodes = 100
len_of_episode = 30
max_load = 5
beta = 5
alpha = 0.0015
learning_rate =  1e-07
discount_rate = 0.95
gamma_decay = 3.3e-06
batch_size = 128
epochs = 2
nS = 2*beta+2
nA = 2**beta - 1
exploit_or_explore = []
epsilon_curve=[]
episode_access_rate = []
avg_waiting_time = []
latencies = []
deviations = []
rewards = []
action = []
load_arr = []